// This file is auto-generated by @hey-api/openapi-ts

export type Answer = {
    u_id?: string;
    content: string;
    checked?: boolean;
};

export type APIStatus = 20000 | 50001 | 50000;

export type Body_sign_in_api_sign_in_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type GetPaperResponse = {
    request_id?: string;
    status?: APIStatus;
    paper: TestPaper_Output;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type PostSubmitResponse = {
    request_id?: string;
    status?: APIStatus;
    score: number;
    user: UserDTO;
};

export type QA = {
    question: Question;
    answers: Array<Answer>;
};

export type Question = {
    u_id?: string;
    content: string;
};

export type TestPaper_Input = {
    paper_id?: string;
    test_id?: string;
    binded: UserDTO;
    q_a_set: Array<QA>;
};

export type TestPaper_Output = {
    paper_id?: string;
    test_id?: string;
    binded: UserDTO;
    q_a_set: Array<QA>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserCreate = {
    name: string;
    password: string;
    user_type?: UType;
};

export type UserDTO = {
    id?: string;
    name?: string;
};

export type UType = 'student' | 'teacher' | 'guest' | 'admin';

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetPaperApiPaperGetResponse = (GetPaperResponse);

export type SubmitPaperApiSubmitPostData = {
    requestBody: TestPaper_Input;
};

export type SubmitPaperApiSubmitPostResponse = (PostSubmitResponse);

export type AnalyzeApiAnalysisGetResponse = (PostSubmitResponse);

export type SignUpApiSignUpPostData = {
    requestBody: UserCreate;
};

export type SignUpApiSignUpPostResponse = (UserDTO);

export type SignInApiSignInPostData = {
    formData: Body_sign_in_api_sign_in_post;
};

export type SignInApiSignInPostResponse = (Token);

export type GetMeApiUserMeGetResponse = (UserDTO);