// This file is auto-generated by @hey-api/openapi-ts

export type Answer = {
    u_id?: string;
    content: string;
    checked?: boolean;
};

export type APIStatus = 20000 | 50001 | 50000;

export type GetPaperResponse = {
    request_id?: string;
    status?: APIStatus;
    paper: TestPaper_Output;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type PostSubmitResponse = {
    request_id?: string;
    status?: APIStatus;
    score: number;
    user: User;
};

export type QA = {
    question: Question;
    answers: Array<Answer>;
};

export type Question = {
    u_id?: string;
    content: string;
};

export type TestPaper_Input = {
    id?: string;
    binded: User;
    q_a_set: Array<QA>;
};

export type TestPaper_Output = {
    id?: string;
    binded: User;
    q_a_set: Array<QA>;
};

export type User = {
    id?: string;
    name?: string;
    password?: string;
    user_type?: UType;
};

export type UType = 'student' | 'teacher' | 'guest' | 'admin';

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetPaperApiPaperGetResponse = (GetPaperResponse);

export type SubmitPaperApiSubmitPostData = {
    requestBody: TestPaper_Input;
};

export type SubmitPaperApiSubmitPostResponse = (PostSubmitResponse);