/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSubmitImport } from './routes/_layout/submit'
import { Route as LayoutResultImport } from './routes/_layout/result'
import { Route as LayoutPaperImport } from './routes/_layout/paper'
import { Route as LayoutAdminImport } from './routes/_layout/admin'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSubmitRoute = LayoutSubmitImport.update({
  path: '/submit',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutResultRoute = LayoutResultImport.update({
  path: '/result',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPaperRoute = LayoutPaperImport.update({
  path: '/paper',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/paper': {
      preLoaderRoute: typeof LayoutPaperImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/result': {
      preLoaderRoute: typeof LayoutResultImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/submit': {
      preLoaderRoute: typeof LayoutSubmitImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutPaperRoute,
    LayoutResultRoute,
    LayoutSubmitRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  SignupRoute,
])

/* prettier-ignore-end */
